rules:
  "preset-ja-technical-writing":
    "no-exclamation-question-mark":
      "allowFullWidthExclamation": true
      "allowFullWidthQuestion": true
    "preset-ja-spacing":
      "ja-space-between-half-and-full-width":
        space: "always"
        exceptPunctuation: true